[package]
name = "demo-test"
version = "0.1.0"
authors = ["KentaHara <blanc.et.noir.rinc@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
